# Generated by Django 2.0.5 on 2018-10-10 21:31

from django.db import migrations

def seed(apps, schema_editor):
    Student = apps.get_model('afterschool', 'Student')
    Student(name="Gisselle Kumar",year_in_school="K",id_pic="../../images/default.png",student_id=1).save()
    Student(name="Misty Vitali",year_in_school="K",id_pic="../../images/default.png",student_id=2).save()
    Student(name="Ea Kranz",year_in_school="K",id_pic="../../images/default.png",student_id=3).save()
    Student(name="Borislav Fashingbauer",year_in_school="K",id_pic="../../images/default.png",student_id=4).save()
    Student(name="Kolos MacLean",year_in_school="K",id_pic="../../images/default.png",student_id=5).save()
    Student(name="Ephesius Lukeson",year_in_school="1",id_pic="../../images/default.png",student_id=6).save()
    Student(name="Pála Taverna",year_in_school="1",id_pic="../../images/default.png",student_id=7).save()
    Student(name="Rémi Matos",year_in_school="1",id_pic="../../images/default.png",student_id=8).save()
    Student(name="Susumu Chaykovsky",year_in_school="1",id_pic="../../images/default.png",student_id=9).save()
    Student(name="Heikki Tapia",year_in_school="1",id_pic="../../images/default.png",student_id=10).save()
    Student(name="Anastasio Roussel",year_in_school="2",id_pic="../../images/default.png",student_id=11).save()
    Student(name="Stefanie Ferrer",year_in_school="2",id_pic="../../images/default.png",student_id=12).save()
    Student(name="Gennadius Sundén",year_in_school="2",id_pic="../../images/default.png",student_id=13).save()
    Student(name="Katerina Andersen",year_in_school="2",id_pic="../../images/default.png",student_id=14).save()
    Student(name="Gunvor Mac Cába",year_in_school="2",id_pic="../../images/default.png",student_id=15).save()
    Student(name="Nkosazana Agthoven",year_in_school="3",id_pic="../../images/default.png",student_id=16).save()
    Student(name="Seydou Niemec",year_in_school="3",id_pic="../../images/default.png",student_id=17).save()
    Student(name="Felicianus Seward",year_in_school="3",id_pic="../../images/default.png",student_id=18).save()
    Student(name="Keti Pfenning",year_in_school="3",id_pic="../../images/default.png",student_id=19).save()
    Student(name="Boža Paternoster",year_in_school="3",id_pic="../../images/default.png",student_id=20).save()
    Student(name="Dutch Ferrer",year_in_school="4",id_pic="../../images/default.png",student_id=21).save()
    Student(name="Röwşen Pavić",year_in_school="4",id_pic="../../images/default.png",student_id=22).save()
    Student(name="Kalliope Berglund",year_in_school="4",id_pic="../../images/default.png",student_id=23).save()
    Student(name="Anghel Grimaldi",year_in_school="4",id_pic="../../images/default.png",student_id=24).save()
    Student(name="Chandan Mendelssohn",year_in_school="4",id_pic="../../images/default.png",student_id=25).save()
    Student(name="Christie Claes",year_in_school="5",id_pic="../../images/default.png",student_id=26).save()
    Student(name="Inka Banes",year_in_school="5",id_pic="../../images/default.png",student_id=27).save()
    Student(name="Mechislav Gray",year_in_school="5",id_pic="../../images/default.png",student_id=28).save()
    Student(name="Maas Matevosian",year_in_school="5",id_pic="../../images/default.png",student_id=29).save()
    Student(name="Ali Adamson",year_in_school="5",id_pic="../../images/default.png",student_id=30).save()
    Student(name="Nebuchadnezzar Snell",year_in_school="6",id_pic="../../images/default.png",student_id=31).save()
    Student(name="Chetan Darrell",year_in_school="6",id_pic="../../images/default.png",student_id=32).save()
    Student(name="Katia Weiner",year_in_school="6",id_pic="../../images/default.png",student_id=33).save()
    Student(name="Skyler Zelenka",year_in_school="6",id_pic="../../images/default.png",student_id=34).save()
    Student(name="Józsua Bergström",year_in_school="6",id_pic="../../images/default.png",student_id=35).save()
    Student(name="Radcliff Forrest",year_in_school="7",id_pic="../../images/default.png",student_id=36).save()
    Student(name="Asta Daniel",year_in_school="7",id_pic="../../images/default.png",student_id=37).save()
    Student(name="Wiktor Watt",year_in_school="7",id_pic="../../images/default.png",student_id=38).save()
    Student(name="Ju Kedzierski",year_in_school="7",id_pic="../../images/default.png",student_id=39).save()
    Student(name="Leland Parri",year_in_school="7",id_pic="../../images/default.png",student_id=40).save()
    Student(name="Arielle Alden",year_in_school="8",id_pic="../../images/default.png",student_id=41).save()
    Student(name="Nathalie Cabrera",year_in_school="8",id_pic="../../images/default.png",student_id=42).save()
    Student(name="Ridwan Blake",year_in_school="8",id_pic="../../images/default.png",student_id=43).save()
    Student(name="Dagr Székely",year_in_school="8",id_pic="../../images/default.png",student_id=44).save()
    Student(name="Filibert Tapia",year_in_school="8",id_pic="../../images/default.png",student_id=45).save()


def fallow(apps, schema_editor):
    Preference = apps.get_model('afterschool', 'Student')
    Preference.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('afterschool', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(seed, fallow)
    ]
